#!/usr/bin/env bash
# shellcheck shell=bash

BRIDGE_SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
BRIDGE_HOME="${BRIDGE_HOME:-$BRIDGE_SCRIPT_DIR}"
BRIDGE_ROSTER_FILE="${BRIDGE_ROSTER_FILE:-$BRIDGE_HOME/agent-roster.sh}"
BRIDGE_ROSTER_LOCAL_FILE="${BRIDGE_ROSTER_LOCAL_FILE:-$BRIDGE_HOME/agent-roster.local.sh}"
BRIDGE_STATE_DIR="${BRIDGE_STATE_DIR:-$BRIDGE_HOME/state}"
BRIDGE_ACTIVE_AGENT_DIR="${BRIDGE_ACTIVE_AGENT_DIR:-$BRIDGE_STATE_DIR/agents}"
BRIDGE_HISTORY_DIR="${BRIDGE_HISTORY_DIR:-$BRIDGE_STATE_DIR/history}"
BRIDGE_WORKTREE_META_DIR="${BRIDGE_WORKTREE_META_DIR:-$BRIDGE_STATE_DIR/worktrees}"
BRIDGE_ACTIVE_ROSTER_TSV="${BRIDGE_ACTIVE_ROSTER_TSV:-$BRIDGE_STATE_DIR/active-roster.tsv}"
BRIDGE_ACTIVE_ROSTER_MD="${BRIDGE_ACTIVE_ROSTER_MD:-$BRIDGE_STATE_DIR/active-roster.md}"
BRIDGE_DAEMON_PID_FILE="${BRIDGE_DAEMON_PID_FILE:-$BRIDGE_STATE_DIR/daemon.pid}"
BRIDGE_DAEMON_LOG="${BRIDGE_DAEMON_LOG:-$BRIDGE_STATE_DIR/daemon.log}"
BRIDGE_DAEMON_INTERVAL="${BRIDGE_DAEMON_INTERVAL:-5}"
BRIDGE_TASK_DB="${BRIDGE_TASK_DB:-$BRIDGE_STATE_DIR/tasks.db}"
BRIDGE_WORKTREE_ROOT="${BRIDGE_WORKTREE_ROOT:-$HOME/.agent-bridge/worktrees}"

RED='\033[0;31m'
# shellcheck disable=SC2034
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'
BRIDGE_MANAGED_MARKER="Managed by agent-bridge. Regenerated by ab."
BRIDGE_LEGACY_MANAGED_MARKER="Managed by cc-bridge. Regenerated by ab."

bridge_die() {
  echo -e "${RED}[오류] $*${NC}" >&2
  exit 1
}

bridge_warn() {
  echo -e "${YELLOW}[경고] $*${NC}" >&2
}

bridge_info() {
  echo -e "${CYAN}$*${NC}"
}

bridge_init_dirs() {
  mkdir -p \
    "$BRIDGE_HOME" \
    "$BRIDGE_STATE_DIR" \
    "$BRIDGE_ACTIVE_AGENT_DIR" \
    "$BRIDGE_HISTORY_DIR" \
    "$BRIDGE_WORKTREE_META_DIR" \
    "$BRIDGE_WORKTREE_ROOT" \
    "$BRIDGE_LOG_DIR" \
    "$BRIDGE_SHARED_DIR" \
    "$BRIDGE_TASK_NOTE_DIR"
}

bridge_require_python() {
  if command -v python3 >/dev/null 2>&1; then
    return 0
  fi

  bridge_die "python3가 필요합니다."
}

bridge_now_iso() {
  bridge_require_python
  python3 - <<'PY'
from datetime import datetime, timezone
print(datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"))
PY
}

bridge_nonce() {
  bridge_require_python
  python3 - <<'PY'
import secrets

print(secrets.token_hex(8))
PY
}

bridge_sha1() {
  local text="$1"

  bridge_require_python
  python3 - "$text" <<'PY'
import hashlib
import sys

print(hashlib.sha1(sys.argv[1].encode("utf-8")).hexdigest())
PY
}

bridge_queue_cli() {
  bridge_require_python
  python3 "$BRIDGE_SCRIPT_DIR/bridge-queue.py" "$@"
}

bridge_reset_roster_maps() {
  unset BRIDGE_AGENT_IDS BRIDGE_AGENT_DESC BRIDGE_AGENT_ENGINE BRIDGE_AGENT_SESSION
  unset BRIDGE_AGENT_WORKDIR BRIDGE_AGENT_LAUNCH_CMD BRIDGE_AGENT_ACTION
  unset BRIDGE_AGENT_SOURCE BRIDGE_AGENT_META_FILE BRIDGE_AGENT_LOOP
  unset BRIDGE_AGENT_CONTINUE BRIDGE_AGENT_SESSION_ID BRIDGE_AGENT_HISTORY_KEY
  unset BRIDGE_AGENT_CREATED_AT BRIDGE_AGENT_UPDATED_AT

  declare -g -a BRIDGE_AGENT_IDS=()
  declare -g -A BRIDGE_AGENT_DESC=()
  declare -g -A BRIDGE_AGENT_ENGINE=()
  declare -g -A BRIDGE_AGENT_SESSION=()
  declare -g -A BRIDGE_AGENT_WORKDIR=()
  declare -g -A BRIDGE_AGENT_LAUNCH_CMD=()
  declare -g -A BRIDGE_AGENT_ACTION=()
  declare -g -A BRIDGE_AGENT_SOURCE=()
  declare -g -A BRIDGE_AGENT_META_FILE=()
  declare -g -A BRIDGE_AGENT_LOOP=()
  declare -g -A BRIDGE_AGENT_CONTINUE=()
  declare -g -A BRIDGE_AGENT_SESSION_ID=()
  declare -g -A BRIDGE_AGENT_HISTORY_KEY=()
  declare -g -A BRIDGE_AGENT_CREATED_AT=()
  declare -g -A BRIDGE_AGENT_UPDATED_AT=()
}

bridge_add_agent_id_if_missing() {
  local agent="$1"
  local existing

  for existing in "${BRIDGE_AGENT_IDS[@]}"; do
    if [[ "$existing" == "$agent" ]]; then
      return 0
    fi
  done

  BRIDGE_AGENT_IDS+=("$agent")
}

bridge_validate_agent_name() {
  local name="$1"
  [[ "$name" =~ ^[A-Za-z0-9._-]+$ ]]
}

bridge_join_quoted() {
  local out=""
  local arg
  local quoted

  for arg in "$@"; do
    printf -v quoted '%q' "$arg"
    out+="${out:+ }${quoted}"
  done

  printf '%s' "$out"
}

bridge_project_root_for_path() {
  local path="$1"

  if git -C "$path" rev-parse --show-toplevel >/dev/null 2>&1; then
    git -C "$path" rev-parse --show-toplevel | sed 's#/*$##'
    return 0
  fi

  (cd "$path" && pwd -P)
}

bridge_path_relative_to_root() {
  local path="$1"
  local root="$2"

  bridge_require_python
  python3 - "$path" "$root" <<'PY'
import os
import sys

path = os.path.realpath(sys.argv[1])
root = os.path.realpath(sys.argv[2])

try:
    rel = os.path.relpath(path, root)
except Exception:
    rel = "."

print(rel)
PY
}

bridge_agent_project_root() {
  local agent="$1"
  bridge_project_root_for_path "$(bridge_agent_workdir "$agent")"
}

bridge_history_file_for_agent() {
  local agent="$1"
  bridge_history_file_for "$(bridge_agent_engine "$agent")" "$agent" "$(bridge_agent_workdir "$agent")"
}

bridge_agent_history_exists() {
  local agent="$1"
  local file

  file="$(bridge_history_file_for_agent "$agent")"
  [[ -f "$file" ]]
}

bridge_worktree_slug_for_project() {
  local project_root="$1"
  local base
  local hash

  base="$(basename "$project_root")"
  base="${base//[^A-Za-z0-9._-]/-}"
  hash="$(bridge_sha1 "$project_root")"
  printf '%s-%s' "$base" "${hash:0:8}"
}

bridge_worktree_branch_for_agent() {
  local agent="$1"
  local branch

  branch="$agent"
  branch="${branch//[^A-Za-z0-9._-]/-}"
  printf 'agent-bridge/%s' "$branch"
}

bridge_worktree_root_for() {
  local project_root="$1"
  local agent="$2"
  local slug

  slug="$(bridge_worktree_slug_for_project "$project_root")"
  printf '%s/%s/%s' "$BRIDGE_WORKTREE_ROOT" "$slug" "$agent"
}

bridge_worktree_launch_dir_for() {
  local source_workdir="$1"
  local agent="$2"
  local project_root relpath worktree_root

  project_root="$(bridge_project_root_for_path "$source_workdir")"
  relpath="$(bridge_path_relative_to_root "$source_workdir" "$project_root")"
  worktree_root="$(bridge_worktree_root_for "$project_root" "$agent")"

  if [[ "$relpath" == "." ]]; then
    printf '%s' "$worktree_root"
  else
    printf '%s/%s' "$worktree_root" "$relpath"
  fi
}

bridge_worktree_meta_key() {
  local project_root="$1"
  local agent="$2"
  bridge_sha1 "${project_root}|${agent}"
}

bridge_worktree_meta_file_for() {
  local project_root="$1"
  local agent="$2"
  local key

  key="$(bridge_worktree_meta_key "$project_root" "$agent")"
  printf '%s/%s--%s.env' "$BRIDGE_WORKTREE_META_DIR" "$agent" "${key:0:12}"
}

bridge_write_worktree_metadata() {
  local engine="$1"
  local agent="$2"
  local source_workdir="$3"
  local project_root="$4"
  local worktree_root="$5"
  local worktree_workdir="$6"
  local branch="$7"
  local meta_file
  local relpath
  local created_at
  local updated_at

  meta_file="$(bridge_worktree_meta_file_for "$project_root" "$agent")"
  relpath="$(bridge_path_relative_to_root "$source_workdir" "$project_root")"
  created_at="$(date +%s)"
  updated_at="$(bridge_now_iso)"

  mkdir -p "$(dirname "$meta_file")"
  cat >"$meta_file" <<EOF
WORKTREE_AGENT=$(printf '%q' "$agent")
WORKTREE_ENGINE=$(printf '%q' "$engine")
WORKTREE_SOURCE_WORKDIR=$(printf '%q' "$source_workdir")
WORKTREE_PROJECT_ROOT=$(printf '%q' "$project_root")
WORKTREE_RELATIVE_DIR=$(printf '%q' "$relpath")
WORKTREE_ROOT=$(printf '%q' "$worktree_root")
WORKTREE_WORKDIR=$(printf '%q' "$worktree_workdir")
WORKTREE_BRANCH=$(printf '%q' "$branch")
WORKTREE_CREATED_AT=$(printf '%q' "$created_at")
WORKTREE_UPDATED_AT=$(printf '%q' "$updated_at")
EOF
}

bridge_list_worktrees() {
  local file
  local WORKTREE_AGENT=""
  local WORKTREE_ENGINE=""
  local WORKTREE_PROJECT_ROOT=""
  local WORKTREE_ROOT=""
  local WORKTREE_WORKDIR=""
  local WORKTREE_BRANCH=""
  local active
  local printed=0

  shopt -s nullglob
  for file in "$BRIDGE_WORKTREE_META_DIR"/*.env; do
    WORKTREE_AGENT=""
    WORKTREE_ENGINE=""
    WORKTREE_PROJECT_ROOT=""
    WORKTREE_ROOT=""
    WORKTREE_WORKDIR=""
    WORKTREE_BRANCH=""
    # shellcheck source=/dev/null
    source "$file"
    [[ -z "$WORKTREE_AGENT" ]] && continue
    printed=1
    active="no"
    if bridge_agent_exists "$WORKTREE_AGENT" && bridge_agent_is_active "$WORKTREE_AGENT"; then
      active="yes"
    fi
    printf '%s | engine=%s | active=%s | branch=%s | repo=%s | root=%s | workdir=%s\n' \
      "$WORKTREE_AGENT" \
      "${WORKTREE_ENGINE:-unknown}" \
      "$active" \
      "${WORKTREE_BRANCH:--}" \
      "${WORKTREE_PROJECT_ROOT:--}" \
      "${WORKTREE_ROOT:--}" \
      "${WORKTREE_WORKDIR:--}"
  done
  shopt -u nullglob

  if [[ "$printed" == "0" ]]; then
    echo "(등록된 agent-bridge worktree 없음)"
  fi
}

bridge_static_agents_for_project_engine() {
  local project_root="$1"
  local engine="$2"
  local agent
  local agent_root

  for agent in "${BRIDGE_AGENT_IDS[@]}"; do
    [[ "$(bridge_agent_source "$agent")" == "static" ]] || continue
    [[ "$(bridge_agent_engine "$agent")" == "$engine" ]] || continue
    agent_root="$(bridge_agent_project_root "$agent")"
    [[ "$agent_root" == "$project_root" ]] || continue
    if bridge_agent_is_active "$agent"; then
      continue
    fi
    printf '%s\n' "$agent"
  done
}

bridge_source_repo_is_dirty() {
  local project_root="$1"
  [[ -n "$(git -C "$project_root" status --short 2>/dev/null || true)" ]]
}

bridge_prepare_isolated_worktree() {
  local engine="$1"
  local agent="$2"
  local source_workdir="$3"
  local project_root worktree_root worktree_workdir branch

  project_root="$(bridge_project_root_for_path "$source_workdir")"
  if ! git -C "$project_root" rev-parse --show-toplevel >/dev/null 2>&1; then
    bridge_die "git 프로젝트에서만 isolated worktree를 만들 수 있습니다: $source_workdir"
  fi

  worktree_root="$(bridge_worktree_root_for "$project_root" "$agent")"
  worktree_workdir="$(bridge_worktree_launch_dir_for "$source_workdir" "$agent")"
  branch="$(bridge_worktree_branch_for_agent "$agent")"

  if [[ -d "$worktree_root/.git" || -f "$worktree_root/.git" ]]; then
    bridge_write_worktree_metadata "$engine" "$agent" "$source_workdir" "$project_root" "$worktree_root" "$worktree_workdir" "$branch"
    printf '%s' "$worktree_workdir"
    return 0
  fi

  mkdir -p "$(dirname "$worktree_root")"
  if bridge_source_repo_is_dirty "$project_root"; then
    bridge_warn "원본 작업트리에 미커밋 변경이 있습니다. 새 worktree는 현재 HEAD 기준으로 생성됩니다: $project_root"
  fi

  if git -C "$project_root" show-ref --verify --quiet "refs/heads/$branch"; then
    git -C "$project_root" worktree add "$worktree_root" "$branch" >/dev/null
  else
    git -C "$project_root" worktree add -b "$branch" "$worktree_root" HEAD >/dev/null
  fi

  bridge_write_worktree_metadata "$engine" "$agent" "$source_workdir" "$project_root" "$worktree_root" "$worktree_workdir" "$branch"
  printf '%s' "$worktree_workdir"
}

bridge_infer_current_agent() {
  local session=""
  local current_dir
  local agent
  local match=""

  if [[ -n "${TMUX:-}" ]]; then
    session="$(tmux display-message -p '#S' 2>/dev/null || true)"
    if [[ -n "$session" ]] && bridge_agent_exists "$session"; then
      printf '%s' "$session"
      return 0
    fi
  fi

  current_dir="$(pwd -P)"
  for agent in "${BRIDGE_AGENT_IDS[@]}"; do
    if [[ "$(bridge_agent_workdir "$agent")" == "$current_dir" ]]; then
      if [[ -n "$match" ]]; then
        return 1
      fi
      match="$agent"
    fi
  done

  if [[ -n "$match" ]]; then
    printf '%s' "$match"
    return 0
  fi

  return 1
}

bridge_resolve_agent() {
  local requested="${1:-}"
  local resolved=""

  if [[ -n "$requested" ]]; then
    bridge_require_agent "$requested"
    printf '%s' "$requested"
    return 0
  fi

  if resolved="$(bridge_infer_current_agent)"; then
    printf '%s' "$resolved"
    return 0
  fi

  bridge_die "에이전트를 자동 추론할 수 없습니다. --agent 또는 명시적 agent 인자를 사용하세요."
}

bridge_agent_exists() {
  local agent="$1"
  [[ -n "${BRIDGE_AGENT_SESSION[$agent]+x}" ]]
}

bridge_require_agent() {
  local agent="$1"

  if bridge_agent_exists "$agent"; then
    return 0
  fi

  echo "등록된 에이전트:"
  bridge_list_agents >&2
  bridge_die "'$agent'은(는) 등록된 에이전트가 아닙니다."
}

bridge_agent_desc() {
  local agent="$1"
  printf '%s' "${BRIDGE_AGENT_DESC[$agent]-}"
}

bridge_agent_engine() {
  local agent="$1"
  printf '%s' "${BRIDGE_AGENT_ENGINE[$agent]-unknown}"
}

bridge_agent_source() {
  local agent="$1"
  printf '%s' "${BRIDGE_AGENT_SOURCE[$agent]-static}"
}

bridge_agent_session() {
  local agent="$1"
  printf '%s' "${BRIDGE_AGENT_SESSION[$agent]-}"
}

bridge_agent_workdir() {
  local agent="$1"
  printf '%s' "${BRIDGE_AGENT_WORKDIR[$agent]-}"
}

bridge_agent_loop() {
  local agent="$1"
  printf '%s' "${BRIDGE_AGENT_LOOP[$agent]-1}"
}

bridge_agent_continue() {
  local agent="$1"
  printf '%s' "${BRIDGE_AGENT_CONTINUE[$agent]-1}"
}

bridge_agent_session_id() {
  local agent="$1"
  printf '%s' "${BRIDGE_AGENT_SESSION_ID[$agent]-}"
}

bridge_agent_meta_file() {
  local agent="$1"
  printf '%s' "${BRIDGE_AGENT_META_FILE[$agent]-}"
}

bridge_agent_history_key() {
  local agent="$1"
  printf '%s' "${BRIDGE_AGENT_HISTORY_KEY[$agent]-}"
}

bridge_agent_action() {
  local agent="$1"
  local action="$2"
  printf '%s' "${BRIDGE_AGENT_ACTION["$agent:$action"]-}"
}

bridge_list_actions() {
  local agent="$1"
  local key

  for key in "${!BRIDGE_AGENT_ACTION[@]}"; do
    if [[ "$key" == "$agent:"* ]]; then
      printf '%s\n' "${key#*:}"
    fi
  done | sort -u
}

bridge_tmux_session_exists() {
  local session="$1"
  tmux has-session -t "$session" 2>/dev/null
}

bridge_agent_is_active() {
  local agent="$1"
  local session

  session="$(bridge_agent_session "$agent")"
  [[ -n "$session" ]] && bridge_tmux_session_exists "$session"
}

bridge_list_agents() {
  local agent
  local actions
  local active

  for agent in "${BRIDGE_AGENT_IDS[@]}"; do
    actions=$(bridge_list_actions "$agent" | paste -sd ',' -)
    if [[ -z "$actions" ]]; then
      actions="-"
    fi

    if bridge_agent_is_active "$agent"; then
      active="yes"
    else
      active="no"
    fi

    printf '  %s — %s\n' "$agent" "$(bridge_agent_desc "$agent")"
    printf '    engine=%s | session=%s | workdir=%s | source=%s | active=%s | loop=%s | actions=%s\n' \
      "$(bridge_agent_engine "$agent")" \
      "$(bridge_agent_session "$agent")" \
      "$(bridge_agent_workdir "$agent")" \
      "$(bridge_agent_source "$agent")" \
      "$active" \
      "$(bridge_agent_loop "$agent")" \
      "$actions"
  done
}

bridge_active_agent_ids() {
  local agent

  for agent in "${BRIDGE_AGENT_IDS[@]}"; do
    if bridge_agent_is_active "$agent"; then
      printf '%s\n' "$agent"
    fi
  done
}

bridge_active_agent_id_by_index() {
  local target_index="$1"
  local current_index=0
  local agent

  [[ "$target_index" =~ ^[0-9]+$ ]] || return 1
  (( target_index >= 1 )) || return 1

  while IFS= read -r agent; do
    [[ -z "$agent" ]] && continue
    current_index=$((current_index + 1))
    if [[ "$current_index" == "$target_index" ]]; then
      printf '%s' "$agent"
      return 0
    fi
  done < <(bridge_active_agent_ids)

  return 1
}

bridge_list_active_agents_numbered() {
  local index=0
  local agent
  local session_id
  local printed=0
  local summary_output=""
  local -A queue_counts=()
  local -A claimed_counts=()

  if summary_output="$(bridge_queue_cli summary --format tsv 2>/dev/null)"; then
    while IFS=$'\t' read -r agent_name queued claimed _blocked _active _idle _last_seen _last_nudge _session _engine _workdir; do
      [[ -z "$agent_name" ]] && continue
      queue_counts["$agent_name"]="$queued"
      claimed_counts["$agent_name"]="$claimed"
    done <<<"$summary_output"
  fi

  while IFS= read -r agent; do
    [[ -z "$agent" ]] && continue
    index=$((index + 1))
    printed=1
    session_id="$(bridge_agent_session_id "$agent")"
    if [[ -z "$session_id" ]]; then
      session_id="-"
    fi

    printf '%d. %s | engine=%s | tmux=%s | cwd=%s | source=%s | loop=%s | inbox=%s | claimed=%s | session_id=%s\n' \
      "$index" \
      "$agent" \
      "$(bridge_agent_engine "$agent")" \
      "$(bridge_agent_session "$agent")" \
      "$(bridge_agent_workdir "$agent")" \
      "$(bridge_agent_source "$agent")" \
      "$(bridge_agent_loop "$agent")" \
      "${queue_counts[$agent]-0}" \
      "${claimed_counts[$agent]-0}" \
      "$session_id"
  done < <(bridge_active_agent_ids)

  if [[ "$printed" == "0" ]]; then
    echo "(활성 bridge 에이전트 세션 없음)"
  fi
}

bridge_refresh_runtime_state() {
  if [[ -f "$BRIDGE_HOME/bridge-sync.sh" ]]; then
    bash "$BRIDGE_HOME/bridge-sync.sh" >/dev/null 2>&1 || true
  else
    bridge_render_active_roster
  fi
}

bridge_kill_agent_session() {
  local agent="$1"
  local session

  session="$(bridge_agent_session "$agent")"
  if [[ -z "$session" ]]; then
    bridge_warn "tmux 세션 정보가 없습니다: $agent"
    return 1
  fi

  if ! bridge_tmux_session_exists "$session"; then
    bridge_warn "이미 종료된 세션입니다: $agent/$session"
    return 1
  fi

  tmux kill-session -t "$session"
  bridge_info "[info] killed ${agent}/${session}"
}

bridge_kill_active_agent_by_index() {
  local index="$1"
  local agent

  if ! agent="$(bridge_active_agent_id_by_index "$index")"; then
    bridge_die "활성 에이전트 번호가 올바르지 않습니다: $index"
  fi

  bridge_kill_agent_session "$agent"
  bridge_refresh_runtime_state
}

bridge_kill_all_active_agents() {
  local -a agents=()
  local agent

  mapfile -t agents < <(bridge_active_agent_ids)
  if [[ ${#agents[@]} -eq 0 ]]; then
    echo "[info] 종료할 활성 bridge 에이전트 세션이 없습니다."
    return 0
  fi

  for agent in "${agents[@]}"; do
    bridge_kill_agent_session "$agent" || true
  done

  bridge_refresh_runtime_state
}

bridge_require_tmux_session() {
  local session="$1"

  if bridge_tmux_session_exists "$session"; then
    return 0
  fi

  echo "현재 활성 세션:"
  tmux list-sessions 2>/dev/null || echo "  (없음)"
  bridge_die "tmux 세션 '$session'이 존재하지 않습니다."
}

bridge_attach_tmux_session() {
  local session="$1"

  if [[ -n "${TMUX:-}" ]]; then
    exec tmux switch-client -t "$session"
  fi

  exec tmux attach -t "$session"
}

bridge_tmux_bootstrap_session_options() {
  local session="$1"
  tmux set-option -t "$session" mouse on >/dev/null 2>&1 || true
  tmux set-option -t "$session" history-limit 10000 >/dev/null 2>&1 || true
}

bridge_tmux_paste_and_submit() {
  local session="$1"
  local text="$2"
  local buffer_name

  buffer_name="bridge-send-$$-$(bridge_nonce)"
  tmux set-buffer -b "$buffer_name" "$text"
  tmux paste-buffer -d -p -b "$buffer_name" -t "$session"

  # Give terminal TUIs a brief moment to process the paste before submit.
  sleep 0.05
  tmux send-keys -t "$session" C-m
}

bridge_tmux_type_and_submit() {
  local session="$1"
  local text="$2"
  local line
  local first_line=1

  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ $first_line -eq 0 ]]; then
      tmux send-keys -t "$session" C-j
    fi
    if [[ -n "$line" ]]; then
      tmux send-keys -t "$session" -l "$line"
    fi
    first_line=0
  done <<< "$text"

  # Give terminal TUIs a brief moment to process literal input before submit.
  sleep 0.05
  tmux send-keys -t "$session" C-m
}

bridge_tmux_send_and_submit() {
  local session="$1"
  local engine="$2"
  local text="$3"

  case "$engine" in
    claude)
      bridge_tmux_type_and_submit "$session" "$text"
      ;;
    *)
      bridge_tmux_paste_and_submit "$session" "$text"
      ;;
  esac
}

bridge_capture_recent() {
  local session="$1"
  local lines="${2:-30}"
  tmux capture-pane -t "$session" -p -S "-$lines"
}

bridge_sanitize_text() {
  printf '%s' "$1" | tr -d '\000-\011\013-\037'
}

bridge_history_key_for() {
  local engine="$1"
  local name="$2"
  local workdir="$3"
  bridge_sha1 "${engine}|${name}|${workdir}"
}

bridge_history_file_for() {
  local engine="$1"
  local name="$2"
  local workdir="$3"
  local key

  key="$(bridge_history_key_for "$engine" "$name" "$workdir")"
  printf '%s/%s--%s--%s.env' "$BRIDGE_HISTORY_DIR" "$name" "$engine" "$key"
}

bridge_dynamic_agent_file_for() {
  local name="$1"
  printf '%s/%s.env' "$BRIDGE_ACTIVE_AGENT_DIR" "$name"
}

bridge_project_skill_dir_for() {
  local engine="$1"
  local workdir="$2"

  case "$engine" in
    codex)
      printf '%s/.agents/skills/agent-bridge-project' "$workdir"
      ;;
    claude)
      printf '%s/.claude/skills/agent-bridge-project' "$workdir"
      ;;
    *)
      return 1
      ;;
  esac
}

bridge_legacy_project_skill_dir_for() {
  local engine="$1"
  local workdir="$2"

  case "$engine" in
    codex)
      printf '%s/.agents/skills/cc-bridge-project' "$workdir"
      ;;
    claude)
      printf '%s/.claude/skills/cc-bridge-project' "$workdir"
      ;;
    *)
      return 1
      ;;
  esac
}

bridge_is_managed_markdown() {
  local file="$1"
  grep -Fq "$BRIDGE_MANAGED_MARKER" "$file" || grep -Fq "$BRIDGE_LEGACY_MANAGED_MARKER" "$file"
}

bridge_migrate_legacy_project_skill_dir() {
  local engine="$1"
  local workdir="$2"
  local new_dir legacy_dir legacy_skill_file

  new_dir="$(bridge_project_skill_dir_for "$engine" "$workdir")"
  legacy_dir="$(bridge_legacy_project_skill_dir_for "$engine" "$workdir")"
  legacy_skill_file="${legacy_dir}/SKILL.md"

  if [[ ! -d "$legacy_dir" || -e "$new_dir" || ! -f "$legacy_skill_file" ]]; then
    return 0
  fi

  if ! bridge_is_managed_markdown "$legacy_skill_file"; then
    return 0
  fi

  mkdir -p "$(dirname "$new_dir")"
  mv "$legacy_dir" "$new_dir"
}

bridge_render_project_bridge_reference() {
  local bridge_home="$1"

  cat <<EOF
# Agent Bridge Quick Reference

<!-- ${BRIDGE_MANAGED_MARKER} -->

Use this guide when a task involves tmux-based agent coordination through \`${bridge_home}\`.

## Roster

- Bridge dashboard: \`${bridge_home}/ab status\`
- Live dashboard watch mode: \`${bridge_home}/ab status --watch\`
- Active bridge agents with numeric indexes: \`${bridge_home}/ab list\`
- Agent inbox and claimed counts are included in \`ab list\`
- Static roster: \`bash ${bridge_home}/bridge-start.sh --list\`
- Live roster with active sessions: \`cat ${bridge_home}/state/active-roster.md\`
- Static definitions: \`cat ${bridge_home}/agent-roster.sh\`

## Start Or Resume Agents

- Start a rostered agent: \`bash ${bridge_home}/bridge-start.sh codex-developer\`
- Wake a rostered role through \`ab\` by using the static agent name directly: \`${bridge_home}/ab --codex --name codex-developer\`
- Start an ad hoc Codex agent from the current folder: \`${bridge_home}/ab --codex --name dev\`
- Start an ad hoc Claude agent from the current folder: \`${bridge_home}/ab --claude --name reviewer\`
- Create an isolated git worktree worker from the current folder: \`${bridge_home}/ab --codex --name reviewer-a --prefer new\`
- Reconnect to a Claude-style resume action: \`bash ${bridge_home}/cc-resume.sh tester --wait 5\`

## Task Queue

- Create a queued task: \`${bridge_home}/ab task create --to developer --title "재테스트" --body-file ${bridge_home}/shared/report.md\`
- Check an inbox: \`${bridge_home}/ab inbox developer\`
- Claim a task: \`${bridge_home}/ab claim 12 --agent developer\`
- Mark a task done: \`${bridge_home}/ab done 12 --agent developer --note "재현 불가"\`
- Hand off a task: \`${bridge_home}/ab handoff 12 --to tester --note "수정 반영 후 재확인 부탁"\`

## Urgent Interrupts

- Send a direct urgent message only when interrupting is necessary: \`bash ${bridge_home}/bridge-send.sh --urgent developer "[TESTER] 프로덕션 장애 확인 필요" --wait 5\`
- List available slash-style actions: \`bash ${bridge_home}/bridge-action.sh --list tester\`
- Trigger a predefined action: \`bash ${bridge_home}/bridge-action.sh tester resume --wait 5\`

## Stop Sessions

- Kill one active bridge session by index: \`${bridge_home}/ab kill 1\`
- Kill every active bridge session managed by the current roster: \`${bridge_home}/ab kill all\`
- List managed worktrees: \`${bridge_home}/ab worktree list\`

## Share Larger Files

- Put long notes or QA reports in \`${bridge_home}/shared/\`
- Prefer task queue entries plus file paths over direct message pastes
- Runtime state under \`${bridge_home}/state/\` and logs under \`${bridge_home}/logs/\` are generated files and should not be hand-edited
EOF
}

bridge_render_codex_project_skill() {
  local bridge_home="$1"

  cat <<EOF
---
name: agent-bridge-project
description: Use when work needs tmux-based multi-agent coordination through \`${bridge_home}\`, including reading the roster, starting ad hoc workers with \`ab\`, sending messages between agents, triggering predefined actions, or sharing long reports through \`${bridge_home}/shared/\`.
---

<!-- ${BRIDGE_MANAGED_MARKER} -->

Use this skill when the task depends on the shared agent bridge in \`${bridge_home}\`.

## Workflow

1. Read the live roster in \`${bridge_home}/state/active-roster.md\` before coordinating with another agent.
2. Use \`bridge-start.sh\` for static roster entries and \`ab\` for ad hoc workers tied to the current folder.
3. If \`ab --name <agent>\` matches a static roster role, it wakes that role instead of creating a new dynamic worker.
4. If the current path belongs to a git project that already has dormant static roles, prefer \`ab --prefer new\` to create an isolated worktree worker rather than sharing the same checkout.
5. Use \`ab status\` for an at-a-glance dashboard, or \`ab status --watch\` for the live TUI.
6. Use the task queue first: \`ab task create\`, \`ab inbox\`, \`ab claim\`, \`ab done\`, and \`ab handoff\`.
7. Reserve \`bridge-send.sh --urgent\` for true interrupts and use \`bridge-action.sh\` only for predefined actions.
8. Store long reports in \`${bridge_home}/shared/\` and send only the path.

## Reference

- Load [references/bridge-commands.md](references/bridge-commands.md) for command patterns and examples.

## Guardrails

- Do not hardcode agent metadata into bridge scripts; static roster data belongs in \`${bridge_home}/agent-roster.sh\`.
- Prefer the live roster over guesswork when identifying active tmux sessions.
- Treat \`${bridge_home}/state/\` and \`${bridge_home}/logs/\` as generated runtime artifacts.
- Prefer queued tasks over direct messages so agents can pull work at task boundaries.
EOF
}

bridge_render_claude_project_skill() {
  local bridge_home="$1"

  cat <<EOF
---
name: agent-bridge-project
description: Use PROACTIVELY when a task involves tmux-based multi-agent coordination through \`${bridge_home}\`, including roster lookup, inter-agent messaging, ad hoc worker startup with \`ab\`, predefined bridge actions, or shared handoff files.
---

<!-- ${BRIDGE_MANAGED_MARKER} -->

Use this skill when work depends on the shared agent bridge in \`${bridge_home}\`.

## Workflow

1. Inspect \`${bridge_home}/state/active-roster.md\` for active agents and session ids.
2. Use \`bridge-start.sh\` for static roster roles and \`ab\` for ad hoc workers in the current folder.
3. If \`ab --name <agent>\` matches a static roster role, it wakes that role instead of creating a new dynamic worker.
4. In git projects with dormant static roles, prefer \`ab --prefer new\` so concurrent workers use isolated worktrees instead of the shared checkout.
5. Use \`ab status\` for a one-shot dashboard or \`ab status --watch\` for the live TUI.
6. Use the queue first: \`ab task create\`, \`ab inbox\`, \`ab claim\`, \`ab done\`, and \`ab handoff\`.
7. Use \`bridge-send.sh --urgent\` only for interruptions that cannot wait for queue pickup, and use \`bridge-action.sh\` for predefined actions.
8. Put long notes in \`${bridge_home}/shared/\` and send the path instead of pasting large blocks.

## Reference

- Read [references/bridge-commands.md](references/bridge-commands.md) for examples and guardrails.

## Guardrails

- Do not edit generated runtime files under \`${bridge_home}/state/\` or \`${bridge_home}/logs/\`.
- Check the static roster in \`${bridge_home}/agent-roster.sh\` before assuming an agent name or action exists.
- Keep urgent interrupts short and move details into task queue entries or shared files.
EOF
}

bridge_write_managed_markdown() {
  local file="$1"
  local label="$2"
  local tmp

  mkdir -p "$(dirname "$file")"
  tmp="$(mktemp)"
  cat >"$tmp"

  if [[ -f "$file" ]] && ! bridge_is_managed_markdown "$file"; then
    bridge_warn "${label} already exists and is not managed by agent-bridge: $file"
    rm -f "$tmp"
    return 1
  fi

  if [[ -f "$file" ]] && cmp -s "$tmp" "$file"; then
    rm -f "$tmp"
    return 0
  fi

  mv "$tmp" "$file"
  bridge_info "[info] ${label}: ${file}"
}

bridge_bootstrap_project_skill() {
  local engine="$1"
  local workdir="$2"
  local skill_dir skill_file reference_file

  bridge_migrate_legacy_project_skill_dir "$engine" "$workdir"

  if ! skill_dir="$(bridge_project_skill_dir_for "$engine" "$workdir")"; then
    return 0
  fi

  skill_file="${skill_dir}/SKILL.md"
  reference_file="${skill_dir}/references/bridge-commands.md"

  case "$engine" in
    codex)
      bridge_render_codex_project_skill "$BRIDGE_HOME" | bridge_write_managed_markdown "$skill_file" "project Codex bridge skill" || return 1
      ;;
    claude)
      bridge_render_claude_project_skill "$BRIDGE_HOME" | bridge_write_managed_markdown "$skill_file" "project Claude bridge skill" || return 1
      ;;
    *)
      return 0
      ;;
  esac

  bridge_render_project_bridge_reference "$BRIDGE_HOME" | bridge_write_managed_markdown "$reference_file" "project bridge reference" || return 1
}

bridge_build_dynamic_launch_cmd() {
  local agent="$1"
  local engine continue_mode session_id

  engine="$(bridge_agent_engine "$agent")"
  continue_mode="$(bridge_agent_continue "$agent")"
  session_id="$(bridge_agent_session_id "$agent")"

  case "$engine" in
    codex)
      if [[ "$continue_mode" == "1" && -n "$session_id" ]]; then
        bridge_join_quoted codex resume "$session_id" --dangerously-bypass-approvals-and-sandbox --no-alt-screen
      else
        bridge_join_quoted codex --dangerously-bypass-approvals-and-sandbox --no-alt-screen
      fi
      ;;
    claude)
      if [[ "$continue_mode" == "1" && -n "$session_id" ]]; then
        bridge_join_quoted claude --resume "$session_id" --dangerously-skip-permissions --name "$agent"
      elif [[ "$continue_mode" == "1" ]]; then
        bridge_join_quoted claude --continue --dangerously-skip-permissions --name "$agent"
      else
        bridge_join_quoted claude --dangerously-skip-permissions --name "$agent"
      fi
      ;;
    *)
      printf '%s' "${BRIDGE_AGENT_LAUNCH_CMD[$agent]-}"
      ;;
  esac
}

bridge_build_resume_launch_cmd() {
  local agent="$1"
  local engine continue_mode session_id

  engine="$(bridge_agent_engine "$agent")"
  continue_mode="$(bridge_agent_continue "$agent")"
  session_id="$(bridge_agent_session_id "$agent")"

  if [[ "$continue_mode" != "1" || -z "$session_id" ]]; then
    return 1
  fi

  case "$engine" in
    codex)
      bridge_join_quoted codex resume "$session_id" --dangerously-bypass-approvals-and-sandbox --no-alt-screen
      ;;
    claude)
      bridge_join_quoted claude --resume "$session_id" --dangerously-skip-permissions --name "$agent"
      ;;
    *)
      return 1
      ;;
  esac
}

bridge_agent_launch_cmd() {
  local agent="$1"
  local fallback=""

  if [[ "$(bridge_agent_source "$agent")" == "dynamic" ]]; then
    if bridge_build_resume_launch_cmd "$agent"; then
      return 0
    fi
    bridge_build_dynamic_launch_cmd "$agent"
    return 0
  fi

  fallback="${BRIDGE_AGENT_LAUNCH_CMD[$agent]-}"
  if bridge_build_resume_launch_cmd "$agent"; then
    return 0
  fi

  printf '%s' "$fallback"
}

bridge_load_dynamic_agent_file() {
  local file="$1"
  local AGENT_ID=""
  local AGENT_DESC=""
  local AGENT_ENGINE=""
  local AGENT_SESSION=""
  local AGENT_WORKDIR=""
  local AGENT_LOOP=""
  local AGENT_CONTINUE=""
  local AGENT_SESSION_ID=""
  local AGENT_HISTORY_KEY=""
  local AGENT_CREATED_AT=""
  local AGENT_UPDATED_AT=""

  # shellcheck source=/dev/null
  source "$file"

  if [[ -z "$AGENT_ID" || -z "$AGENT_ENGINE" || -z "$AGENT_SESSION" || -z "$AGENT_WORKDIR" ]]; then
    return 0
  fi

  bridge_add_agent_id_if_missing "$AGENT_ID"
  BRIDGE_AGENT_DESC["$AGENT_ID"]="${AGENT_DESC:-$AGENT_ID}"
  BRIDGE_AGENT_ENGINE["$AGENT_ID"]="$AGENT_ENGINE"
  BRIDGE_AGENT_SESSION["$AGENT_ID"]="$AGENT_SESSION"
  BRIDGE_AGENT_WORKDIR["$AGENT_ID"]="$AGENT_WORKDIR"
  BRIDGE_AGENT_SOURCE["$AGENT_ID"]="dynamic"
  BRIDGE_AGENT_META_FILE["$AGENT_ID"]="$file"
  BRIDGE_AGENT_LOOP["$AGENT_ID"]="${AGENT_LOOP:-1}"
  BRIDGE_AGENT_CONTINUE["$AGENT_ID"]="${AGENT_CONTINUE:-1}"
  BRIDGE_AGENT_SESSION_ID["$AGENT_ID"]="${AGENT_SESSION_ID:-}"
  BRIDGE_AGENT_HISTORY_KEY["$AGENT_ID"]="${AGENT_HISTORY_KEY:-}"
  BRIDGE_AGENT_CREATED_AT["$AGENT_ID"]="${AGENT_CREATED_AT:-}"
  BRIDGE_AGENT_UPDATED_AT["$AGENT_ID"]="${AGENT_UPDATED_AT:-}"
}

bridge_load_dynamic_agents() {
  local file

  shopt -s nullglob
  for file in "$BRIDGE_ACTIVE_AGENT_DIR"/*.env; do
    bridge_load_dynamic_agent_file "$file"
  done
  shopt -u nullglob
}

bridge_load_static_agent_history() {
  local agent="$1"
  local file
  local AGENT_ID=""
  local AGENT_CONTINUE=""
  local AGENT_SESSION_ID=""
  local AGENT_HISTORY_KEY=""
  local AGENT_CREATED_AT=""
  local AGENT_UPDATED_AT=""

  file="$(bridge_history_file_for_agent "$agent")"
  [[ -f "$file" ]] || return 0

  # shellcheck source=/dev/null
  source "$file"

  if [[ -n "$AGENT_ID" && "$AGENT_ID" != "$agent" ]]; then
    return 0
  fi

  if [[ -n "$AGENT_CONTINUE" ]]; then
    BRIDGE_AGENT_CONTINUE["$agent"]="$AGENT_CONTINUE"
  fi
  if [[ -n "$AGENT_SESSION_ID" ]]; then
    BRIDGE_AGENT_SESSION_ID["$agent"]="$AGENT_SESSION_ID"
  fi
  if [[ -n "$AGENT_HISTORY_KEY" ]]; then
    BRIDGE_AGENT_HISTORY_KEY["$agent"]="$AGENT_HISTORY_KEY"
  fi
  if [[ -n "$AGENT_CREATED_AT" ]]; then
    BRIDGE_AGENT_CREATED_AT["$agent"]="$AGENT_CREATED_AT"
  fi
  if [[ -n "$AGENT_UPDATED_AT" ]]; then
    BRIDGE_AGENT_UPDATED_AT["$agent"]="$AGENT_UPDATED_AT"
  fi
}

bridge_load_static_histories() {
  local agent

  for agent in "${BRIDGE_AGENT_IDS[@]}"; do
    [[ "$(bridge_agent_source "$agent")" == "static" ]] || continue
    bridge_load_static_agent_history "$agent"
  done
}

bridge_load_roster() {
  local agent

  if [[ ! -f "$BRIDGE_ROSTER_FILE" ]]; then
    bridge_die "로스터 파일이 없습니다: $BRIDGE_ROSTER_FILE"
  fi

  bridge_reset_roster_maps

  # shellcheck source=/dev/null
  source "$BRIDGE_ROSTER_FILE"

  if [[ -f "$BRIDGE_ROSTER_LOCAL_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$BRIDGE_ROSTER_LOCAL_FILE"
  fi

  if [[ -z "${BRIDGE_AGENT_IDS+x}" || ${#BRIDGE_AGENT_IDS[@]} -eq 0 ]]; then
    bridge_die "BRIDGE_AGENT_IDS가 비어 있습니다: $BRIDGE_ROSTER_FILE"
  fi

  : "${BRIDGE_LOG_DIR:=$BRIDGE_HOME/logs}"
  : "${BRIDGE_SHARED_DIR:=$BRIDGE_HOME/shared}"
  : "${BRIDGE_MAX_MESSAGE_LEN:=500}"
  : "${BRIDGE_TASK_NOTE_DIR:=$BRIDGE_SHARED_DIR/tasks}"
  : "${BRIDGE_TASK_LEASE_SECONDS:=900}"
  : "${BRIDGE_TASK_IDLE_NUDGE_SECONDS:=120}"
  : "${BRIDGE_TASK_NUDGE_COOLDOWN_SECONDS:=900}"
  : "${BRIDGE_TASK_HEARTBEAT_WINDOW_SECONDS:=300}"

  bridge_init_dirs

  for agent in "${BRIDGE_AGENT_IDS[@]}"; do
    BRIDGE_AGENT_SOURCE["$agent"]="${BRIDGE_AGENT_SOURCE[$agent]-static}"
    BRIDGE_AGENT_LOOP["$agent"]="${BRIDGE_AGENT_LOOP[$agent]-1}"
    BRIDGE_AGENT_CONTINUE["$agent"]="${BRIDGE_AGENT_CONTINUE[$agent]-1}"
    BRIDGE_AGENT_HISTORY_KEY["$agent"]="${BRIDGE_AGENT_HISTORY_KEY[$agent]-$(bridge_history_key_for "$(bridge_agent_engine "$agent")" "$agent" "$(bridge_agent_workdir "$agent")")}"
  done

  bridge_load_static_histories
  bridge_load_dynamic_agents
}

bridge_dynamic_agent_ids() {
  local agent

  for agent in "${BRIDGE_AGENT_IDS[@]}"; do
    if [[ "$(bridge_agent_source "$agent")" == "dynamic" ]]; then
      printf '%s\n' "$agent"
    fi
  done
}

bridge_write_agent_state_file() {
  local agent="$1"
  local file="$2"
  local desc engine session workdir loop_mode continue_mode session_id history_key created_at updated_at

  desc="$(bridge_agent_desc "$agent")"
  engine="$(bridge_agent_engine "$agent")"
  session="$(bridge_agent_session "$agent")"
  workdir="$(bridge_agent_workdir "$agent")"
  loop_mode="$(bridge_agent_loop "$agent")"
  continue_mode="$(bridge_agent_continue "$agent")"
  session_id="$(bridge_agent_session_id "$agent")"
  history_key="$(bridge_agent_history_key "$agent")"
  created_at="${BRIDGE_AGENT_CREATED_AT[$agent]-$(date +%s)}"
  updated_at="$(bridge_now_iso)"

  # shellcheck disable=SC2034
  BRIDGE_AGENT_UPDATED_AT["$agent"]="$updated_at"

  mkdir -p "$(dirname "$file")"
  cat >"$file" <<EOF
AGENT_ID=$(printf '%q' "$agent")
AGENT_DESC=$(printf '%q' "$desc")
AGENT_ENGINE=$(printf '%q' "$engine")
AGENT_SESSION=$(printf '%q' "$session")
AGENT_WORKDIR=$(printf '%q' "$workdir")
AGENT_LOOP=$(printf '%q' "$loop_mode")
AGENT_CONTINUE=$(printf '%q' "$continue_mode")
AGENT_SESSION_ID=$(printf '%q' "$session_id")
AGENT_HISTORY_KEY=$(printf '%q' "$history_key")
AGENT_CREATED_AT=$(printf '%q' "$created_at")
AGENT_UPDATED_AT=$(printf '%q' "$updated_at")
EOF
}

bridge_write_dynamic_agent_file() {
  local agent="$1"
  local file="${2:-$(bridge_dynamic_agent_file_for "$agent")}"
  bridge_write_agent_state_file "$agent" "$file"
}

bridge_archive_dynamic_agent() {
  local agent="$1"
  local history_file

  history_file="$(bridge_history_file_for_agent "$agent")"
  bridge_write_agent_state_file "$agent" "$history_file"
}

bridge_remove_dynamic_agent_file() {
  local agent="$1"
  local file

  file="$(bridge_agent_meta_file "$agent")"
  if [[ -n "$file" && -f "$file" ]]; then
    rm -f "$file"
  fi
}

bridge_persist_agent_state() {
  local agent="$1"

  if [[ "$(bridge_agent_source "$agent")" == "dynamic" ]]; then
    bridge_write_dynamic_agent_file "$agent"
  fi
  bridge_write_agent_state_file "$agent" "$(bridge_history_file_for_agent "$agent")"
}

bridge_detect_claude_session_id() {
  local workdir="$1"
  local since_ms="${2:-0}"
  local exclude_csv="${3:-}"

  python3 - "$workdir" "$since_ms" "$exclude_csv" <<'PY'
import glob
import json
import os
import sys

workdir = sys.argv[1]
since_ms = int(sys.argv[2] or "0")
if 0 < since_ms < 10**11:
    since_ms *= 1000
exclude = {x for x in sys.argv[3].split(",") if x}
best = None

for path in glob.glob(os.path.expanduser("~/.claude/sessions/*.json")):
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except Exception:
        continue
    sid = data.get("sessionId")
    cwd = data.get("cwd")
    started = int(data.get("startedAt") or 0)
    if cwd != workdir or not sid or sid in exclude:
        continue
    if since_ms and started < max(0, since_ms - 300000):
        continue
    if best is None or started > best[0]:
        best = (started, sid)

print(best[1] if best else "")
PY
}

bridge_detect_codex_session_id() {
  local workdir="$1"
  local since_epoch="${2:-0}"
  local exclude_csv="${3:-}"

  python3 - "$workdir" "$since_epoch" "$exclude_csv" <<'PY'
import datetime as dt
import glob
import json
import os
import sys

workdir = sys.argv[1]
since_epoch = float(sys.argv[2] or "0")
if since_epoch > 10**11:
    since_epoch /= 1000.0
exclude = {x for x in sys.argv[3].split(",") if x}
paths = sorted(
    glob.glob(os.path.expanduser("~/.codex/sessions/**/*.jsonl"), recursive=True),
    key=lambda p: os.path.getmtime(p),
    reverse=True,
)[:500]
best = None

def parse_iso(value: str) -> float:
    if not value:
        return 0.0
    value = value.replace("Z", "+00:00")
    try:
        return dt.datetime.fromisoformat(value).timestamp()
    except Exception:
        return 0.0

for path in paths:
    try:
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                try:
                    obj = json.loads(line)
                except Exception:
                    continue
                if obj.get("type") != "session_meta":
                    continue
                payload = obj.get("payload", {})
                sid = payload.get("id")
                cwd = payload.get("cwd")
                ts = parse_iso(payload.get("timestamp"))
                if cwd != workdir or not sid or sid in exclude:
                    break
                if since_epoch and ts < max(0.0, since_epoch - 300.0):
                    break
                if best is None or ts > best[0]:
                    best = (ts, sid)
                break
    except Exception:
        continue

print(best[1] if best else "")
PY
}

bridge_detect_session_id() {
  local engine="$1"
  local workdir="$2"
  local since_hint="$3"
  local exclude_csv="${4:-}"

  case "$engine" in
    codex)
      bridge_detect_codex_session_id "$workdir" "$since_hint" "$exclude_csv"
      ;;
    claude)
      bridge_detect_claude_session_id "$workdir" "$since_hint" "$exclude_csv"
      ;;
    *)
      printf '%s' ""
      ;;
  esac
}

bridge_refresh_agent_session_id() {
  local agent="$1"
  local attempts="${2:-8}"
  local sleep_seconds="${3:-0.25}"
  local since_hint sid detected exclude_csv
  local -a excluded=()
  local other try_index

  sid="$(bridge_agent_session_id "$agent")"
  if [[ -n "$sid" ]]; then
    printf '%s' "$sid"
    return 0
  fi

  since_hint="${BRIDGE_AGENT_CREATED_AT[$agent]-$(date +%s)}"
  for ((try_index = 0; try_index < attempts; try_index += 1)); do
    excluded=()
    for other in "${BRIDGE_AGENT_IDS[@]}"; do
      [[ "$other" == "$agent" ]] && continue
      sid="$(bridge_agent_session_id "$other")"
      if [[ -n "$sid" ]]; then
        excluded+=("$sid")
      fi
    done
    exclude_csv="$(IFS=,; echo "${excluded[*]}")"

    detected="$(bridge_detect_session_id \
      "$(bridge_agent_engine "$agent")" \
      "$(bridge_agent_workdir "$agent")" \
      "$since_hint" \
      "$exclude_csv")"

    if [[ -n "$detected" ]]; then
      # shellcheck disable=SC2034
      BRIDGE_AGENT_SESSION_ID["$agent"]="$detected"
      bridge_persist_agent_state "$agent"
      printf '%s' "$detected"
      return 0
    fi

    sleep "$sleep_seconds"
  done

  return 1
}

bridge_daemon_pid() {
  if [[ -f "$BRIDGE_DAEMON_PID_FILE" ]]; then
    cat "$BRIDGE_DAEMON_PID_FILE"
  fi
}

bridge_daemon_is_running() {
  local pid

  pid="$(bridge_daemon_pid)"
  [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null
}

bridge_tmux_session_activity_ts() {
  local session="$1"
  tmux display-message -p -t "$session" '#{session_activity}' 2>/dev/null || true
}

bridge_write_agent_snapshot() {
  local file="$1"
  local agent
  local active
  local session
  local activity

  {
    echo -e "agent\tengine\tsession\tworkdir\tactive\tsession_activity_ts"
    for agent in "${BRIDGE_AGENT_IDS[@]}"; do
      active=0
      session="$(bridge_agent_session "$agent")"
      activity=""
      if bridge_agent_is_active "$agent"; then
        active=1
        activity="$(bridge_tmux_session_activity_ts "$session")"
      fi

      echo -e "${agent}\t$(bridge_agent_engine "$agent")\t${session}\t$(bridge_agent_workdir "$agent")\t${active}\t${activity}"
    done
  } >"$file"
}

bridge_write_roster_status_snapshot() {
  local file="$1"
  local agent
  local active
  local session

  {
    echo -e "agent\tengine\tsession\tworkdir\tsource\tactive"
    for agent in "${BRIDGE_AGENT_IDS[@]}"; do
      active=0
      session="$(bridge_agent_session "$agent")"
      if bridge_agent_is_active "$agent"; then
        active=1
      fi

      echo -e "${agent}\t$(bridge_agent_engine "$agent")\t${session}\t$(bridge_agent_workdir "$agent")\t$(bridge_agent_source "$agent")\t${active}"
    done
  } >"$file"
}

bridge_task_daemon_step() {
  local snapshot_file="$1"
  bridge_queue_cli daemon-step \
    --snapshot "$snapshot_file" \
    --lease-seconds "$BRIDGE_TASK_LEASE_SECONDS" \
    --heartbeat-window "$BRIDGE_TASK_HEARTBEAT_WINDOW_SECONDS" \
    --idle-threshold "$BRIDGE_TASK_IDLE_NUDGE_SECONDS" \
    --nudge-cooldown "$BRIDGE_TASK_NUDGE_COOLDOWN_SECONDS"
}

bridge_task_note_nudge() {
  local agent="$1"
  bridge_queue_cli note-nudge --agent "$agent" >/dev/null
}

bridge_render_active_roster() {
  local tmp_tsv tmp_md updated session_id
  local agent
  local summary_output=""
  local -A queue_counts=()
  local -A claimed_counts=()

  if summary_output="$(bridge_queue_cli summary --format tsv 2>/dev/null)"; then
    while IFS=$'\t' read -r agent_name queued claimed _blocked _active _idle _last_seen _last_nudge _session _engine _workdir; do
      [[ -z "$agent_name" ]] && continue
      queue_counts["$agent_name"]="$queued"
      claimed_counts["$agent_name"]="$claimed"
    done <<<"$summary_output"
  fi

  tmp_tsv="$(mktemp)"
  tmp_md="$(mktemp)"
  updated="$(bridge_now_iso)"

  {
    echo -e "agent\tengine\tsession\tcwd\tsource\tloop\tcontinue\tqueued\tclaimed\tsession_id\tupdated_at"
    for agent in "${BRIDGE_AGENT_IDS[@]}"; do
      if ! bridge_agent_is_active "$agent"; then
        continue
      fi

      session_id="$(bridge_agent_session_id "$agent")"
      echo -e "${agent}\t$(bridge_agent_engine "$agent")\t$(bridge_agent_session "$agent")\t$(bridge_agent_workdir "$agent")\t$(bridge_agent_source "$agent")\t$(bridge_agent_loop "$agent")\t$(bridge_agent_continue "$agent")\t${queue_counts[$agent]-0}\t${claimed_counts[$agent]-0}\t${session_id}\t${updated}"
    done
  } >"$tmp_tsv"

  {
    echo "# Active Agent Roster"
    echo
    echo "updated_at: ${updated}"
    echo
    echo "| agent | engine | session | source | loop | inbox | claimed | cwd | session_id |"
    echo "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"
    for agent in "${BRIDGE_AGENT_IDS[@]}"; do
      if ! bridge_agent_is_active "$agent"; then
        continue
      fi

      session_id="$(bridge_agent_session_id "$agent")"
      echo "| ${agent} | $(bridge_agent_engine "$agent") | $(bridge_agent_session "$agent") | $(bridge_agent_source "$agent") | $(bridge_agent_loop "$agent") | ${queue_counts[$agent]-0} | ${claimed_counts[$agent]-0} | $(bridge_agent_workdir "$agent") | ${session_id} |"
    done
  } >"$tmp_md"

  mv "$tmp_tsv" "$BRIDGE_ACTIVE_ROSTER_TSV"
  mv "$tmp_md" "$BRIDGE_ACTIVE_ROSTER_MD"
}
